name: wan21
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch>=2.4.0
  - torchvision>=0.19.0
  - tqdm
  - imageio
  - imageio-ffmpeg
  - numpy>=1.23.5,<2
  - pip
  - pip:
    - opencv-python>=4.9.0.80
    - diffusers>=0.31.0
    - transformers>=4.49.0
    - tokenizers>=0.20.3
    - accelerate>=1.1.1
    - easydict
    - ftfy
    - dashscope
    - flash_attn
    - gradio>=5.0.0
